### ISSUE TITLE
My custom theme fails to highlight the variable names

### ISSUE THREAD

**Issue by fincardona** [JuliaEditorSupport/julia-emacs#57] opened 2018-10-08 14:55 UTC
Hello, 
I usually use a custom theme where the variable names are highlighted in orange. I do it by putting the command `'(font-lock-variable-name-face ((t (:foreground "orange red"))))` in my `custom-theme.el` file and it works when I write python code. However, it apparently fails whit julia-mode. Do you have any suggestions? 
Thanks a lot.

**Comment by non-Jedi** [comment] 2019-10-15 15:54
See also #77

This mode doesn't currently look for variable assignment in `julia-font-lock-keywards`. If you are interested in adding this functionality, the implementation for python in "progmodes/python.el" which came with your emacs distribution looks like a reasonable place to start.

**Comment by non-Jedi** [comment] 2019-11-15 14:36
Duplicate of #2. Can be closed.

**Comment by tpapp** [comment] 2019-12-25 08:50
Yes, closing this as a duplicate.

**Closed by tpapp** 2019-12-25 08:50 UTC
