### ISSUE TITLE
Incorrect highlighting for identifiers ending in bang

### ISSUE THREAD

**Issue by rjpower4** [JuliaEditorSupport/julia-emacs#129] opened 2020-06-07 05:25 UTC
The syntax highlighting is failing for functions and variables ending with an `!`. Like: 

![image](https://user-images.githubusercontent.com/25042796/83961076-b62c4180-a85d-11ea-9987-4e3d05e32b73.png)

**Comment by non-Jedi** [comment] 2020-07-09 18:22
`!` is set as "symbol" syntax which should not be font-locked in any special way. I cannot reproduce this. Can you show the output `describe-char` on both the `!` and the `x`?

`julia-function-regex` also correctly captures both `word` and `symbol` syntax. I think this must be caused by something outside of julia-mode.

**Comment by rjpower4** [comment] 2020-08-04 07:01
The `describe-char` for the `!` on the `x!` is:

![image](https://user-images.githubusercontent.com/25042796/89263017-8780dc00-d5fe-11ea-8a3f-09e540fcfb9f.png)

Is this coming from somewhere other than `julia-mode`? Sorry, not super proficient at emacs hacking. If it is, I can move along.

**Comment by non-Jedi** [comment] 2020-08-04 13:27
Yes. `julia-mode` *definitely* wouldn't be fontifying `!` as `font-lock-type-face`. Just to double-check that it's definitely not `julia-mode` causing this, can you reproduce by running `emacs -q` and then evaling:

```elisp
(add-to-list 'load-path "/path/to/julia-mode/folder")
(require 'julia-mode)
```

**Comment by rjpower4** [comment] 2020-08-04 15:12
Running without the config and loading `julia-mode` as you wrote does in fact yield correct highlighting. So the issue is outside of `julia-mode`. Thanks for your help! This issue can be closed and I'll update it for reference if I track down what exactly is causing it if you'd like.

**Comment by ronisbr** [comment] 2020-08-19 00:31
This is a bug in Doom emacs. It should be fixed when this is merged:

https://github.com/hlissner/doom-emacs/pull/3776

I think this issue can be closed.

**Comment by rjpower4** [comment] 2020-08-19 01:29
Awesome, thanks!

**Closed** 2020-08-20 02:32 UTC
